; [database_1]
; host = localhost
; port = 5432
; dbname = blocking_check
; user = manoj_anumalla
; password = 
; schema_name = data_monitoring

[database_2]
host = 10.50.168.126
port = 5432
dbname = rpx
user = tds_etl_app
password = tds_etl_app-dev
schema_name=data_monitoring