; [database_1]
; host = XXXX
; port = 5432
; dbname = XXX
; user = XX
; password = XXX
; schema_name = XXXX

; [database_2]
; host = localhost
; port = 5432
; dbname = blocking_check
; user = manoj_anumalla
; password = 
; schema_name = data_init